Repository tdlight-team/tdlight-telegram-bot-api, pull requests merged in 2020-12, with the labels that each got.

#23 More docs improvements.
  README.md
Labels: documentation

#24 Stats: hide sensible data
  README.md
  docker-entrypoint.sh
  telegram-bot-api/ClientManager.cpp
  telegram-bot-api/ClientParameters.h
  telegram-bot-api/telegram-bot-api.cpp
Labels: enhancement

#29 Fixed directory path of installation tutorial
  README.md
Labels: documentation

#33 Fix crash with service messages
  telegram-bot-api/Client.cpp
Labels: bug
