Repository tdlight-team/tdlight-telegram-bot-api, pull requests merged in 2021-01, with the labels that each got.

#25 User only methods
  telegram-bot-api/Client.cpp
  telegram-bot-api/Client.h
  telegram-bot-api/ClientManager.cpp
Labels: enhancement

#28 Add Swagger Docs on Github pages
  .github/workflows/docs-gh-pages.yml
  .github/workflows/validate-swagger.yml
  icons/favicon-16x16.png
  icons/favicon-196x196.png
  icons/favicon-32x32.png
  tdlight-api-openapi.yaml
Labels: documentation

#45 Use own build Instructions Generator
  .github/workflows/docs-gh-pages.yml
  README.md
  build.html
Labels: documentation

#50 Fix healtcheck fail when TELEGRAM_STAT is not set
  Dockerfile
Labels: bug

#22 Stats: json format
  telegram-bot-api/ClientManager.cpp
  telegram-bot-api/ClientManager.h
  telegram-bot-api/HttpStatConnection.cpp
  telegram-bot-api/HttpStatConnection.h
  telegram-bot-api/Stats.cpp
  telegram-bot-api/Stats.h
  telegram-bot-api/StatsJson.h
Labels: enhancement
